server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://rm-bp178t58v5e5n0c9too.mysql.rds.aliyuncs.com:3306/tututu?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimeZone=GMT%2B8
    username: tututu
    password: Aa123456
    driver-class-name: com.mysql.jdbc.Driver
  #静态资源配置
  resources:
    static-locations: file:${web.upload-path},file:${web.root-path}/static,classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-spring-macro-helpers: false
    expose-session-attributes: false
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: file:${web.root-path}/templates
    settings:
      number_format: 0.##
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      datetime_format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: classpath*:com/ruice/**/model/*.class
web:
  upload-path: F:/ruiceImg/upload/
  root-path: ${user.dir}/src/main/webapp
#日志配置文件
logging:
  config: classpath:logback-dev.xml